apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computer-frontend
  template:
    metadata:
      labels:
        app: computer-frontend
    spec:
      containers:
        - name: frontend
          image: matrusaisuresh/computer-frontend:v1
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service"

