apiVersion: v1
kind: Service
metadata:
  name: phones-service
  labels:
    app: phones
spec:
  type: ClusterIP
  selector:
    app: phones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
